[package]
name = "roguelike"
version = "0.1.0"
authors = ["Elvio Pedroso Martinelli <elviomartinelli@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.9"
tcod = "0.15"
